version: '3'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.0.3-alpine
    ports:
      - '6379:6379'
    volumes:
      - ~/docker/volumes/redis:/data
    command: redis-server --appendonly yes